package com.example.tp1android;

import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

public class LongTextC extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.longtextact);
        TextView text = (TextView) findViewById(R.id.textView2);
        String paragra = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a odio vitae massa eleifend tincidunt. Cras mi erat, tincidunt ut lobortis eget, euismod ac est. Nullam tristique tellus nec nulla dapibus fermentum. Nunc et consectetur orci. Nullam ut arcu elit. Nunc enim lacus, interdum id enim a, ultricies iaculis nibh. Ut convallis venenatis fringilla.\n" +
                "\n" +
                "Cras iaculis justo lorem, a euismod nisi auctor id. Sed congue urna ac neque convallis feugiat. Vivamus posuere pretium nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras vel cursus quam, vitae accumsan dui. Pellentesque nulla risus, placerat et libero ac, porta condimentum ipsum. Nam rutrum lectus nec malesuada rhoncus. Ut varius eu leo eget malesuada. Suspendisse porttitor magna et tortor bibendum posuere. Donec auctor pulvinar eleifend. Etiam maximus ex eget nulla sollicitudin, et suscipit lorem sodales. Sed mattis purus mauris, sit amet volutpat est gravida a. Donec dignissim diam mi. Nam a sapien fringilla, commodo magna at, iaculis elit. Nam eleifend tellus vehicula dignissim euismod.\n" +
                "\n" +
                "Curabitur scelerisque, augue et sollicitudin bibendum, nisl est posuere magna, id tristique ante est eu erat. Integer ut vulputate ligula, vel posuere ante. Maecenas sollicitudin felis dui, ac sagittis nisi rutrum nec. Vestibulum sit amet ipsum dapibus velit interdum dapibus. Vivamus eu pulvinar magna, eleifend luctus leo. Aliquam sit amet sem eget lacus dignissim elementum at id tortor. Etiam pharetra in massa in vestibulum. Morbi non nunc volutpat, posuere ex quis, fermentum velit. Nulla ipsum arcu, porttitor ac sapien eget, lacinia rutrum lacus. Nulla eget blandit purus. Phasellus at facilisis est. Duis ut scelerisque velit, eget congue lacus.\n" +
                "\n" +
                "Sed in libero pellentesque, finibus mauris ut, consequat ante. Nulla aliquet sem in vulputate eleifend. Aenean justo lectus, consequat et pulvinar sit amet, laoreet in ligula. Nunc faucibus lacus tortor, eu feugiat tortor dictum sed. Praesent tincidunt laoreet erat ac cursus. Curabitur eu turpis venenatis, vestibulum enim et, accumsan eros. Vivamus maximus condimentum tristique. Integer consectetur ligula at neque semper pulvinar. Praesent ornare nunc faucibus, pellentesque dui eu, volutpat urna. Nulla commodo tristique est sit amet vulputate. Donec commodo metus sed dolor efficitur, ut ornare purus pharetra.\n" +
                "\n" +
                "Fusce lorem sapien, ultricies non venenatis in, interdum vel diam. Maecenas porta, nunc in blandit sagittis, erat justo tincidunt quam, in convallis neque eros blandit eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum quis ipsum quam. Suspendisse sit amet purus porta justo ultrices cursus. Nam sed quam blandit libero mattis hendrerit. Sed semper vehicula ante, id accumsan ante mattis non. Nulla placerat felis ac mi volutpat viverra. Maecenas sed enim vitae ex consectetur malesuada. Nullam sed dapibus magna, vestibulum tincidunt orci. Sed placerat nulla a nisi congue, et ultrices ligula tempus. Sed vel nibh vel nisl scelerisque fermentum non eu diam. Nulla at metus nec sapien lobortis feugiat nec non libero.\n" +
                "\n" +
                "Vivamus finibus pretium justo, sed tincidunt sem sodales in. Nam nisl nibh, iaculis sed faucibus ut, gravida ac metus. Pellentesque fringilla nisl id cursus efficitur. Aenean facilisis velit ante, vitae sodales sem consequat nec. In accumsan neque volutpat, dignissim eros sed, elementum magna. Sed varius luctus lobortis. Pellentesque vel euismod sapien. Suspendisse urna purus, tempus feugiat dolor in, aliquam vehicula ligula. Nam laoreet tempor efficitur. Praesent vel orci quis augue semper dapibus ac vitae leo. Donec ut dapibus augue. Proin sodales id felis non varius. Vivamus lobortis sapien vehicula dolor elementum convallis. Donec pharetra a massa at aliquam. Nunc felis libero, malesuada eu pellentesque cursus, mollis sit amet sem. In eu libero velit.\n" +
                "\n" +
                "In hac habitasse platea dictumst. Morbi diam ante, venenatis et sapien vel, volutpat lobortis lorem. Cras cursus hendrerit lorem vel facilisis. Nulla nisi neque, luctus a pulvinar gravida, facilisis vitae odio. Sed sit amet posuere diam. Morbi nec ex placerat urna convallis tincidunt et a leo. In ut volutpat neque. Pellentesque placerat a tellus id tempus. Proin id lectus velit. Curabitur vulputate elit eget rhoncus aliquam. Ut ullamcorper molestie tempus.\n" +
                "\n" +
                "Suspendisse vel viverra ipsum, non mollis mauris. Maecenas condimentum euismod gravida. Sed congue risus et turpis convallis iaculis. Etiam molestie tincidunt sodales. Morbi augue dui, viverra ut sem ac, lacinia aliquam eros. Etiam a dui nec lacus consequat venenatis sit amet vitae lacus. Duis ut nisl metus. Nulla congue justo quis placerat eleifend. Phasellus sapien lectus, accumsan vitae enim nec, gravida interdum leo.\n" +
                "\n" +
                "Vestibulum ultricies ultricies risus eu efficitur. Etiam ullamcorper et justo elementum pulvinar. Donec auctor cursus libero, in consectetur diam rutrum eu. Nunc justo velit, euismod viverra mattis eget, feugiat a diam. Cras eu elit mi. In sit amet vehicula nisl, vel venenatis sapien. Donec eu nibh id felis porta blandit. Nam ultrices tempor massa, at rhoncus quam semper id. Curabitur dictum felis non justo elementum pellentesque. Vivamus et tincidunt erat. Sed nec dapibus diam.\n" +
                "\n" +
                "Aenean scelerisque tortor non est fermentum, et bibendum velit iaculis. Mauris vulputate bibendum libero. In lorem libero, ultricies quis elit id, tempor tincidunt mauris. Aenean interdum, velit vel scelerisque laoreet, quam felis lacinia mi, ac luctus felis augue et mauris. Donec non condimentum justo, at faucibus sapien. Duis luctus, ex congue finibus ornare, justo diam tempus ligula, ut ornare sem nisi ut ante. Aliquam sed augue neque.\n" +
                "\n" +
                "Curabitur sollicitudin mattis imperdiet. Proin sit amet nulla egestas, tincidunt lorem vitae, rhoncus lectus. Phasellus id finibus arcu. Nullam lacinia enim nisi. Vivamus et elementum urna, eu gravida sem. Sed porta dui tempor ornare imperdiet. Proin eget leo id lacus vestibulum lacinia. Praesent et sagittis sem. Quisque tincidunt quam et viverra fringilla. Quisque eget dapibus magna. Nulla velit felis, laoreet sed tellus vel, rhoncus pretium nunc. Integer a lectus scelerisque, tempus elit in, pulvinar mauris.\n" +
                "\n" +
                "Vivamus tristique augue fringilla egestas sodales. Sed aliquet non lacus quis ullamcorper. Aliquam vitae turpis vel diam iaculis sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi libero augue, tincidunt sed lorem id, lobortis varius nisl. In dignissim elit at quam sodales, ac accumsan massa vestibulum. Etiam a interdum mauris. Aenean tortor eros, gravida a accumsan nec, cursus eu ligula. Vestibulum dolor mi, blandit at suscipit a, luctus in libero.\n" +
                "\n" +
                "Aliquam velit nulla, suscipit sit amet purus quis, feugiat lacinia mi. Fusce congue ante eget quam consequat finibus. Ut tortor tellus, placerat in semper nec, vestibulum sit amet lectus. Praesent dapibus egestas urna eu bibendum. Suspendisse potenti. Aenean tellus felis, egestas id semper a, elementum volutpat nulla. Proin ac orci accumsan, condimentum dui in, pellentesque mi.\n" +
                "\n" +
                "Suspendisse dignissim ante magna, bibendum porttitor mi feugiat vel. Ut venenatis turpis et egestas pretium. Duis nunc justo, tempus et nisl et, congue congue turpis. Nulla facilisi. Fusce eu faucibus tellus. Nulla libero sem, viverra in arcu et, ornare egestas lacus. Nulla id sapien purus.\n" +
                "\n" +
                "Sed varius ullamcorper enim nec iaculis. Phasellus rutrum urna sit amet nisl lacinia eleifend. Vivamus eu elementum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec neque nulla, auctor id vulputate vitae, lobortis sit amet mi. Etiam feugiat lacus eget dolor viverra viverra. Praesent metus ipsum, vulputate nec tincidunt vitae, ullamcorper in felis. Nullam gravida tempor ligula, vel euismod orci placerat ac. Integer consectetur convallis mi nec rutrum. Praesent vitae rutrum justo. Suspendisse sit amet nisl sed turpis scelerisque accumsan non vel diam. Mauris in justo et elit finibus vestibulum et luctus justo. Vivamus interdum, lorem facilisis cursus volutpat, elit diam consequat velit, imperdiet tempor dui massa eu elit. In lacinia placerat metus id ultricies. Proin fermentum leo sed metus sodales ultrices ut in turpis. Maecenas nec sapien sed metus malesuada porttitor sit amet in lectus.\n" +
                "\n" +
                "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean molestie metus at felis congue euismod. Donec vel mattis eros, sit amet vestibulum tortor. Cras sem ante, fringilla at urna in, viverra pulvinar justo. Donec id pulvinar tortor. Sed feugiat purus sit amet dolor cursus interdum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu massa semper, luctus tortor quis, ornare elit. Morbi id ex sed mi pretium euismod eu at orci. Ut semper libero condimentum nunc hendrerit lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
                "\n" +
                "Sed vitae risus nisl. Cras feugiat leo a nunc posuere, sed porttitor nunc tincidunt. Sed tincidunt urna a volutpat mollis. In ex lorem, interdum non dictum eu, vestibulum nec odio. Nulla euismod, massa ac lacinia pretium, dolor erat convallis nibh, et tristique turpis purus et velit. Praesent cursus tincidunt nisi id tincidunt. Nulla ultrices, nulla sed convallis porta, mauris elit iaculis sem, eget pharetra eros nisi vel velit. Sed vel velit dictum, finibus elit et, blandit mi. Vivamus fringilla hendrerit eleifend. Integer in fermentum eros. Cras eget efficitur est, eget luctus felis. Praesent vel dignissim est.\n" +
                "\n" +
                "Sed pretium lorem eu dapibus porta. Donec molestie varius arcu, eget hendrerit nunc dictum porta. Sed faucibus volutpat arcu vitae pulvinar. Curabitur interdum lorem nisi, eleifend porttitor dui volutpat eu. Aliquam erat volutpat. Nunc molestie dui non neque dignissim laoreet. In hac habitasse platea dictumst. Phasellus in tellus purus. Praesent vestibulum sed nibh dapibus ullamcorper. Etiam dapibus cursus tortor, at semper ligula ullamcorper sit amet. Nulla consequat auctor nisi molestie sollicitudin. Nullam hendrerit lobortis est. Ut nec sem vitae ipsum accumsan efficitur. Proin consequat leo vel enim porttitor, at dapibus justo mattis.\n" +
                "\n" +
                "Aliquam lacinia aliquet sem, ac auctor odio. Maecenas et elit eget ipsum lobortis molestie. Aliquam hendrerit massa quis leo feugiat, a posuere ante mollis. Pellentesque bibendum maximus ex, nec placerat massa laoreet eget. Donec volutpat aliquet eros eget fringilla. Phasellus tincidunt a ligula et pharetra. Nam enim mi, sollicitudin quis sapien id, porttitor luctus risus. Praesent vel augue non diam faucibus hendrerit id quis velit. In hac habitasse platea dictumst. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\n" +
                "\n" +
                "Proin dolor mauris, scelerisque in aliquet eu, feugiat vel nulla. Sed ac elementum mauris. Mauris sodales, ipsum vel tristique venenatis, dui justo lobortis mauris, eu varius mi elit et risus. Mauris quis efficitur magna, sed dignissim metus. Nullam et mauris volutpat, sagittis est ut, mattis dui. Aliquam erat volutpat. Curabitur at dui nec felis porttitor sagittis. Vivamus pretium lectus vitae tortor congue, quis condimentum ante tempor. Curabitur vestibulum accumsan orci. Donec non ex quis est dignissim interdum.\n" +
                "\n" +
                "Quisque rhoncus convallis porttitor. Nullam id tempor dui, vitae commodo massa. Nunc in finibus turpis. Sed volutpat euismod leo, facilisis finibus tellus mollis sit amet. Nunc convallis iaculis semper. Ut at dolor auctor, pretium nisi id, ullamcorper ligula. Vestibulum vehicula ullamcorper leo, porttitor laoreet nisi bibendum at. Praesent sed diam eu eros sagittis luctus in vel mauris. Fusce lobortis viverra erat ut euismod.\n" +
                "\n" +
                "Sed vitae erat vitae neque rhoncus mollis a nec purus. Donec aliquet scelerisque lobortis. Mauris sed lacus et lectus condimentum hendrerit non sit amet ligula. Nam eu metus ac augue euismod placerat. Sed accumsan ligula sit amet libero molestie, sed efficitur lectus feugiat. Phasellus tempus arcu sed nibh egestas pretium. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam lectus enim, eleifend quis magna quis, tincidunt egestas nunc. Nulla tempus nec eros eu consequat. Ut vitae magna at est dictum consectetur. Maecenas viverra risus sit amet felis ullamcorper dapibus. Curabitur ac ipsum orci.\n" +
                "\n" +
                "Ut non ullamcorper dui. Integer accumsan volutpat sapien at viverra. Proin ac purus erat. Maecenas ut ligula sed turpis convallis condimentum. Donec non varius nulla. Nullam eget neque quis nulla posuere posuere. Aliquam at varius enim. Cras elementum urna at ante varius ultrices. In tempus dui eget nisl euismod, id vestibulum nisi mattis. Integer tempor semper iaculis. Quisque rutrum lobortis odio, ac sagittis orci consectetur a. Vivamus elementum quam ut ullamcorper imperdiet. Etiam sit amet odio luctus, interdum dui eget, cursus magna.\n" +
                "\n" +
                "Suspendisse posuere sit amet dolor vel fringilla. Duis placerat libero vitae justo eleifend, non suscipit ipsum tempus. Mauris et mi lacinia, porta urna ut, finibus lectus. Aenean imperdiet mauris eget urna pharetra vestibulum. Vestibulum et nulla at turpis gravida consectetur. Ut ligula libero, dapibus sed nibh in, volutpat egestas est. Nulla tristique auctor odio, nec pulvinar quam dignissim in. Curabitur aliquet odio ac purus fermentum dignissim. Sed porta lorem sed feugiat lacinia. Ut condimentum finibus orci ac egestas. Pellentesque eget turpis velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent semper neque quis faucibus euismod. Maecenas tincidunt massa dolor, eu fringilla ex vehicula facilisis. Nulla malesuada tempus venenatis. In vel arcu dictum, tempus metus eget, eleifend lacus.\n" +
                "\n" +
                "Donec hendrerit aliquam libero, nec lobortis purus aliquam ut. In tempor posuere nisl, at molestie tortor faucibus quis. Donec sit amet est sit amet mauris scelerisque porttitor non vitae lacus. Curabitur sed purus eu turpis euismod porta. Integer dictum quam eget semper convallis. Sed vulputate urna et sem volutpat, eget tempus felis mattis. Aenean non odio dictum, pellentesque mauris id, ultricies augue. Pellentesque sit amet egestas nulla, vel porttitor quam. Quisque non efficitur nibh. Aliquam vel purus enim. Mauris hendrerit mi sed viverra consectetur.\n" +
                "\n" +
                "Nullam hendrerit gravida sem sit amet euismod. Donec convallis interdum metus, aliquam pulvinar lectus auctor in. Donec finibus commodo dictum. Integer congue orci ac felis ultrices accumsan. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras facilisis in odio nec aliquet. Mauris id euismod odio, id consequat metus. Aliquam cursus massa nulla, non facilisis leo pellentesque quis. Etiam luctus pellentesque dolor vel mollis. Mauris gravida sed urna et pellentesque. Nunc tellus quam, commodo vel leo vel, sollicitudin molestie urna.\n" +
                "\n" +
                "Suspendisse potenti. Aliquam vel maximus dolor. Suspendisse tempus accumsan ligula et efficitur. Proin euismod nisl lectus. Aliquam erat volutpat. Nunc sed turpis enim. Cras volutpat bibendum suscipit. Maecenas porttitor tempus nisi, efficitur dignissim ex porta a. In libero diam, ornare in turpis vel, porta ultrices risus.\n" +
                "\n" +
                "Nunc ultricies nisl nec gravida facilisis. Aliquam mattis ultrices lobortis. Pellentesque varius euismod purus, quis volutpat sem mattis non. Vivamus nulla sem, fermentum ac est id, vestibulum varius eros. Maecenas velit diam, suscipit sed efficitur sed, luctus vel libero. Sed imperdiet egestas ipsum, vitae rutrum quam feugiat maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas fringilla auctor nulla, a fringilla nibh finibus vel. Pellentesque non ligula convallis, lacinia nulla a, sodales est. Proin quis vulputate est. Suspendisse dignissim nibh nulla, at facilisis massa commodo in. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" +
                "\n" +
                "Nulla euismod laoreet felis porta varius. Donec pretium quam eget tortor malesuada, sit amet eleifend leo consequat. Nunc sodales mi mi, quis dapibus quam suscipit nec. Sed sed pretium tortor. Ut scelerisque leo eu nibh imperdiet, dictum fermentum lacus sollicitudin. Maecenas consequat eros at imperdiet auctor. Vestibulum nisi eros, posuere in sem ac, condimentum sollicitudin turpis. Donec vehicula varius tortor, et auctor lacus mollis ut. Etiam at auctor enim, id tincidunt ante. Nam eget elit orci.\n" +
                "\n" +
                "Duis vitae turpis id ex varius venenatis. In hac habitasse platea dictumst. Duis posuere eget magna at vulputate. Fusce mattis turpis orci, a consequat quam mollis ut. Pellentesque nec libero a nisl suscipit feugiat quis vitae tortor. Maecenas venenatis lacinia accumsan. Nullam in nulla quis est vestibulum tincidunt sit amet vitae metus. Morbi venenatis bibendum diam, eu tincidunt justo ornare tempus.\n" +
                "\n" +
                "Vestibulum a nunc feugiat, condimentum ligula non, fermentum ipsum. Duis nec risus sapien. Fusce aliquam tellus non ligula dignissim molestie. Pellentesque porta lectus urna, in malesuada purus dictum et. Maecenas et commodo dolor, vitae semper ipsum. Integer in nulla feugiat, ullamcorper arcu quis, varius tortor. Nullam cursus vestibulum lacus, dapibus viverra mauris luctus non. Quisque fringilla tellus ut nisl ultrices hendrerit. In mauris tortor, varius a commodo laoreet, euismod a ipsum. Phasellus fringilla risus at convallis mattis. Duis ut quam tincidunt, lobortis ipsum vel, faucibus metus.\n" +
                "\n" +
                "Suspendisse consequat massa vitae metus congue lobortis. Vestibulum cursus odio ac vestibulum varius. Sed bibendum gravida arcu non condimentum. Proin vel tristique risus. Vivamus ac erat eu libero accumsan maximus sit amet a quam. Nam quis massa elementum purus ultricies venenatis. Praesent in ligula vitae ipsum rhoncus aliquet ut id eros. Nulla sit amet nibh felis. Mauris tempor vitae nulla quis lobortis. Suspendisse est turpis, venenatis non metus vitae, scelerisque vulputate nulla. Quisque pretium semper mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum justo enim, euismod vel cursus eget, faucibus at libero. Donec luctus pharetra tortor, et vestibulum odio auctor nec. Nulla felis orci, venenatis et est nec, porttitor rhoncus risus. Mauris ipsum sem, sollicitudin sed lectus eget, fringilla mattis diam.\n" +
                "\n" +
                "Sed ac urna ac enim convallis tempor a non sem. Sed pretium arcu sit amet orci elementum scelerisque. In in nulla non arcu lacinia suscipit a in augue. Donec feugiat aliquet massa et congue. Praesent et enim ullamcorper, volutpat elit ut, blandit purus. Cras dapibus eget metus ut dictum. Donec ac condimentum nisl. Morbi ipsum felis, interdum in eros nec, ultricies rutrum arcu. Aenean nisi neque, gravida ac nisl ut, mattis tincidunt felis. Nulla vulputate venenatis suscipit. Fusce consequat lectus eu aliquet ultrices. Nulla tempus purus non odio rhoncus, vel accumsan libero ullamcorper. Nullam consectetur vestibulum neque, sit amet faucibus nulla luctus et. Aliquam erat volutpat.\n" +
                "\n" +
                "Cras rhoncus diam et venenatis efficitur. Mauris faucibus finibus velit, posuere ornare lorem condimentum tristique. Sed eu tortor ac turpis blandit condimentum. Nam blandit sapien sed orci dapibus scelerisque. Praesent vestibulum ornare eros nec congue. Nulla blandit, risus quis sagittis tristique, ante turpis varius lectus, sit amet tincidunt tellus orci et nulla. Nunc rhoncus id risus sit amet consequat. Duis id tellus laoreet, ornare diam eget, dapibus diam. Phasellus convallis eros scelerisque est molestie egestas in eu lorem. Nulla pharetra faucibus libero eu semper. Etiam sit amet justo vitae lacus luctus imperdiet ut vitae nunc.\n" +
                "\n" +
                "Maecenas pharetra dui a consequat interdum. Etiam eget vestibulum est. Vivamus sagittis eget nisl vitae tempus. Donec vel metus purus. Vestibulum quis pretium purus. Maecenas ornare metus justo, eu tempus dui tristique eu. Donec odio purus, fermentum ut ligula ac, fermentum bibendum velit. Donec molestie, elit eget blandit consequat, magna urna aliquet massa, in condimentum nisl ante eget libero. Nam maximus, dolor convallis aliquet tristique, ante purus gravida dolor, suscipit blandit justo sem viverra nibh. Nam eleifend massa ante, vel vulputate libero hendrerit at. Ut aliquet interdum interdum. Nulla lacus orci, sollicitudin a lectus ullamcorper, hendrerit fringilla quam. Mauris scelerisque, massa in tristique blandit, velit magna posuere augue, ut ullamcorper enim nisi a libero. Phasellus fermentum posuere nisi, eu tincidunt nunc. Quisque a hendrerit lacus.\n" +
                "\n" +
                "Pellentesque auctor eleifend aliquam. Curabitur consectetur, sapien ut ultricies sodales, nisl nisl imperdiet turpis, at suscipit turpis quam vitae sapien. Vivamus vulputate dictum facilisis. Curabitur efficitur, est quis sagittis aliquam, metus sem tincidunt nunc, in euismod nibh magna non purus. Aliquam erat volutpat. Nulla nec accumsan lacus, non vulputate lectus. Nunc non nisi at velit semper sodales. Fusce eget nisi tincidunt, gravida tellus eu, ornare lectus. Nunc efficitur dolor et egestas tincidunt. Sed efficitur venenatis mauris, et congue dolor lobortis vitae. Aenean aliquet turpis et magna laoreet, nec congue dolor ultrices. Pellentesque convallis tincidunt risus, et mattis nisi luctus id.\n" +
                "\n" +
                "Sed in eros tempor, euismod ante quis, iaculis mauris. Proin id cursus metus. Duis hendrerit lobortis lectus fringilla tempor. Phasellus condimentum, libero a rhoncus vulputate, mauris neque dictum felis, et iaculis erat erat nec ante. Nam libero nibh, tristique non nulla ac, hendrerit tincidunt lorem. Ut aliquet lorem ac nisi blandit, ac sagittis est consequat. Sed eget nisi et risus tempor ultricies. Duis finibus interdum tellus vitae ullamcorper. Sed eu ligula sit amet odio luctus porta. Morbi ut mollis turpis. Praesent malesuada nibh eget tellus elementum tristique. Sed neque urna, sollicitudin vel posuere vel, malesuada vel justo. Praesent porta erat mi, eget molestie massa pulvinar elementum. Proin metus lacus, feugiat in quam id, sodales placerat purus. Nam id facilisis enim, sed viverra augue. Aliquam commodo vulputate nisi, ut vulputate tortor pretium sed.\n" +
                "\n" +
                "Phasellus venenatis, lacus non scelerisque facilisis, magna quam semper metus, vel commodo dolor purus quis est. Cras molestie nisl turpis, in euismod augue pulvinar ut. Praesent quis nibh gravida, molestie lectus vitae, facilisis turpis. Nullam vel nisl eget tellus volutpat mollis. Morbi efficitur massa non placerat dapibus. Suspendisse in dapibus dui. Vestibulum fringilla laoreet purus. Integer ornare eros vel vestibulum ultricies.";
        text.setText(paragra);
        text.setMovementMethod(new ScrollingMovementMethod());

    }
}



